param(
    [ValidateSet('regtest','regtest-lan','testnet','mainnet')]
    [string]$Config = 'regtest-lan',
    [switch]$SkipTests,
    [switch]$Sign,
    [string]$CertSubject = '',
    [string]$CertThumbprint = '',
    [string]$TimestampUrl = 'http://timestamp.digicert.com',
    [switch]$BuildInstaller,
    [switch]$SkipPreflight
)

$ErrorActionPreference = 'Stop'
$Root = Split-Path -Parent $PSScriptRoot
Set-Location $Root

$Version = '1.7.2'
$Platform = 'windows-x64'
$UpdateBaseUrl = 'https://download.qubit-coin.io'
$env:QUB_BUILD_CONFIG = $Config

# Avoid VCRUNTIME140.dll deployment failures on clean Windows installs.
# .cargo/config.toml enables crt-static. Keep this explicit for direct script builds,
# but avoid duplicating the flag when the caller already set it.
if (($env:RUSTFLAGS -as [string]) -notmatch 'crt-static') {
    $env:RUSTFLAGS = (($env:RUSTFLAGS, '-C target-feature=+crt-static') -join ' ').Trim()
}

if (-not $SkipTests) {
    cargo test
}

cargo build --release --bin qub-core --target x86_64-pc-windows-msvc
cargo build --release --bin qubd --target x86_64-pc-windows-msvc

function Find-SignTool {
    $candidates = @(
        "$env:ProgramFiles(x86)\Windows Kits\10\bin\*\x64\signtool.exe",
        "$env:ProgramFiles\Windows Kits\10\bin\*\x64\signtool.exe"
    )
    foreach ($pattern in $candidates) {
        $match = Get-ChildItem $pattern -ErrorAction SilentlyContinue | Sort-Object FullName -Descending | Select-Object -First 1
        if ($match) { return $match.FullName }
    }
    return 'signtool.exe'
}

$DistRoot = Join-Path $Root 'dist'
$Dist = Join-Path $DistRoot "QUB-Core-v$Version-$Platform-$Config"
if (Test-Path $Dist) { Remove-Item $Dist -Recurse -Force }
New-Item -ItemType Directory -Force -Path $Dist | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $Dist 'config') | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $Dist 'assets') | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $Dist 'assets\fonts') | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $Dist 'assets\flags') | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $Dist 'tools') | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $DistRoot 'updates') | Out-Null
$ChannelUpdateDir = Join-Path $DistRoot "updates\$Config\windows-x64"
New-Item -ItemType Directory -Force -Path $ChannelUpdateDir | Out-Null

$ReleaseDir = Join-Path $Root 'target\x86_64-pc-windows-msvc\release'
Copy-Item (Join-Path $ReleaseDir 'qub-core.exe') (Join-Path $Dist 'QUB-Core.exe')
Copy-Item (Join-Path $ReleaseDir 'qubd.exe') (Join-Path $Dist 'tools\qubd.exe')
Copy-Item (Join-Path $Root 'config\*.toml') (Join-Path $Dist 'config')
if (Test-Path (Join-Path $Root 'README-MINER-WINDOWS.md')) { Copy-Item (Join-Path $Root 'README-MINER-WINDOWS.md') $Dist }
foreach ($Doc in @(
    'QUB-Public-Release-Checksums-and-Signing-v1.7.2.md',
    'QUB-Public-Release-Checksums-and-Signing-v1.0.0.md',
    'QUB-Windows-Code-Signing-v1.7.2.md',
    'QUB-Windows-Code-Signing-v1.0.0.md',
    'QUB-Mainnet-Release-Readiness-v1.7.2.md',
    'QUB-Mainnet-Release-Readiness-v1.0.0.md',
    'QUB-Automatic-Discovery-Production-Runbook-v1.7.2.md',
    'QUB-Automatic-Discovery-Production-Runbook-v1.0.0.md'
)) {
    $DocPath = Join-Path $Root $Doc
    if (Test-Path $DocPath) { Copy-Item $DocPath $Dist }
}
$AssetsReadme = Join-Path $Root 'assets\README.md'
if (Test-Path $AssetsReadme) {
    Copy-Item $AssetsReadme (Join-Path $Dist 'assets')
} else {
    @"
QUB Core runtime assets

Optional files copied into release bundles when present:
- qubit-coin-logo.png
- jin-coin-logo.png
- mined.mp3
- network-mined.mp3
- mining-on.mp3
- mining-off.png
- mining-off-white.png
- mining-prep.gif
- mining-prep-white.gif
- mining-on.gif
- mining-on-white.gif
- fonts/Ubuntu-BoldItalic.ttf

This fallback README was generated by the release build script because source assets/README.md was missing.
"@ | Set-Content -Encoding UTF8 -Path (Join-Path $Dist 'assets\README.md')
}

foreach ($Asset in @(
    'qubit-coin-logo.png',
    'opening-banner.png',
    'jin-coin-logo.png',
    'mined.mp3',
    'network-mined.mp3',
    'mining-on.mp3',
    'mining-off.png',
    'mining-off-white.png',
    'mining-prep.gif',
    'mining-prep-white.gif',
    'mining-on.gif',
    'mining-on-white.gif',
    'online.png',
    'offline.png',
    'mining-controls.png',
    'mining-controls-white.png',
    'start-mining.png',
    'stop-mining.png',
    'cpu.png',
    'cpu-white.png',
    'gpu.png',
    'gpu-white.png',
    'wallet-address.png',
    'wallet-address-white.png',
    'send.png',
    'success.png',
    'success-white.png',
    'failed.png',
    'failed-white.png',
    'qub.png',
    'jin.png',
    'register-qub.png',
    'danger-zone.png',
    'delete-local-private-keys.png',
    'benchmark.png',
    'benchmark-white.png',
    'settings.png',
    'settings-white.png',
    'dark.png',
    'dark-white.png',
    'light.png',
    'light-white.png',
    'sync.png',
    'qr.png',
    'qr-white.png',
    'qr-scan.png',
    'qr-scan-white.png',
    'live-chain-data.png',
    'live-chain-data-white.png',
    'network.png',
    'network-white.png',
    'height.png',
    'height-white.png',
    'best-block.png',
    'best-block-white.png',
    'mempool-tx.png',
    'mempool-tx-white.png',
    'spendable.png',
    'immature.png',
    'immature-white.png',
    'total-wallet.png',
    'total-wallet-white.png',
    'wallet-keys.png',
    'wallet-keys-white.png',
    'coinbase-maturity.png',
    'coinbase-maturity-white.png',
    'block-target.png',
    'block-target-white.png',
    'next-reward.png',
    'next-reward-white.png',
    'halving-interval.png',
    'halving-interval-white.png',
    'pow-bits.png',
    'pow-bits-white.png',
    'p2p-peers.png',
    'p2p-peers-white.png',
    'qns.png',
    'qns-white.png',
    'data-dir.png',
    'data-dir-white.png',
    'miner-telemetry.png',
    'miner-telemetry-white.png',
    'hashrate.png',
    'hashrate-white.png',
    'total-hashes.png',
    'total-hashes-white.png',
    'cpu-workers.png',
    'cpu-workers-white.png',
    'duty.png',
    'duty-white.png',
    'target-block.png',
    'target-block-white.png',
    'peers-block-stream.png',
    'peers-block-stream-white.png',
    'web-map.png',
    'web-map-white.png',
    'list.png',
    'list-white.png',
    'peers-other-miners.png',
    'peers-other-miners-white.png',
    'recent-global-blocks.png',
    'recent-global-blocks-white.png',
    'your-pending-mined-block.png',
    'your-pending-mined-block-white.png',
    'your-confirmed-mined-block.png',
    'your-confirmed-mined-block-white.png',
    'your-confirmed-mined-block.png.png',
    'your-confirmed-mined-block-white.png.png',
    'updates-available.png',
    'check-now.png',
    'install-and-restart.png',
    'i.png',
    'i-white.png',
    'address-balances.png',
    'address-balances-white.png',
    'crypto.png',
    'crypto-white.png',
    'import-private-key.png',
    'import-private-key-white.png',
    'buy.png',
    'buy-white.png',
    'sell.png',
    'sell-white.png',
    'offer.png',
    'offer-white.png',
    'melt.png',
    'melt-white.png',
    'infuse.png',
    'infuse-white.png',
    'convert.png',
    'convert-white.png',
    'jin-token.png',
    'jin-token-white.png',
    'auction.png',
    'auction-white.png'
)) {
    $Path = Join-Path $Root "assets\$Asset"
    if (Test-Path $Path) { Copy-Item $Path (Join-Path $Dist 'assets') }
}


# Hotfix37 extra GUI assets.
# Duplicates are harmless; SHA256SUMS.txt is generated from actual files in dist.
foreach ($Asset in @(
    'i.png',
    'i-white.png',
    'address-balances.png',
    'address-balances-white.png',
    'crypto.png',
    'crypto-white.png',
    'import-private-key.png',
    'import-private-key-white.png',
    'buy.png',
    'buy-white.png',
    'sell.png',
    'sell-white.png',
    'offer.png',
    'offer-white.png',
    'melt.png',
    'melt-white.png',
    'infuse.png',
    'infuse-white.png',
    'convert.png',
    'convert-white.png',
    'jin-token.png',
    'jin-token-white.png',
    'auction.png',
    'auction-white.png',
    'list-asset.png',
    'list-asset-white.png'
)) {
    $Path = Join-Path $Root "assets\$Asset"
    if (Test-Path $Path) { Copy-Item -Force $Path (Join-Path $Dist 'assets') }
}

# HF102/v1.7.2: copy every runtime asset that exists, not only the legacy allow-list.
# This prevents new bridge/UI icons (eth/usdt/usdc/usdj/enj/subscan/nftio/verified/etc.)
# from appearing in local smoke but missing from live update bundles.
$AssetRoot = Join-Path $Root 'assets'
if (Test-Path $AssetRoot) {
    Get-ChildItem $AssetRoot -Recurse -File | Where-Object {
        $_.Extension.ToLowerInvariant() -in @('.png','.webp','.gif','.mp3','.ttf','.otf','.md')
    } | ForEach-Object {
        $rel = $_.FullName.Substring($AssetRoot.Length).TrimStart('\','/')
        $dest = Join-Path (Join-Path $Dist 'assets') $rel
        $parent = Split-Path -Parent $dest
        if (-not (Test-Path $parent)) { New-Item -ItemType Directory -Force -Path $parent | Out-Null }
        Copy-Item -Force $_.FullName $dest
    }
}

foreach ($Flag in @('en-US.png','el-GR.png','fr-FR.png','de-DE.png','es-ES.png','zh-CN.png','ja-JP.png','ko-KR.png')) {
    $FlagPath = Join-Path $Root "assets\flags\$Flag"
    if (Test-Path $FlagPath) { Copy-Item $FlagPath (Join-Path $Dist 'assets\flags') }
}

$Font = Join-Path $Root 'assets\fonts\Ubuntu-BoldItalic.ttf'
if (Test-Path $Font) { Copy-Item $Font (Join-Path $Dist 'assets\fonts') }

$Cli = @"
@echo off
set "QUB_HOME=%~dp0.."
cd /d "%QUB_HOME%"
"%~dp0qubd.exe" --config "%QUB_HOME%\config\$Config.toml" %*
"@
Set-Content -Encoding ASCII -Path (Join-Path $Dist 'tools\qubd-cli.cmd') -Value $Cli

$SeedLauncher = @"
@echo off
set "QUB_HOME=%~dp0.."
cd /d "%QUB_HOME%"
"%~dp0qubd.exe" --config "%QUB_HOME%\config\$Config.toml" node
"@
Set-Content -Encoding ASCII -Path (Join-Path $Dist 'tools\Start-QUB-Seed-Node.cmd') -Value $SeedLauncher

$SyncOnce = @"
@echo off
set "QUB_HOME=%~dp0.."
cd /d "%QUB_HOME%"
"%~dp0qubd.exe" --config "%QUB_HOME%\config\$Config.toml" sync
"@
Set-Content -Encoding ASCII -Path (Join-Path $Dist 'tools\Sync-QUB-Once.cmd') -Value $SyncOnce

if (-not $SkipPreflight) {
    $PreflightConfig = Join-Path $Dist "config\$Config.toml"
    & (Join-Path $Dist 'tools\qubd.exe') --config $PreflightConfig preflight
    if ($LASTEXITCODE -ne 0) { throw "QUB preflight failed for $Config. Fix config before building a public bundle, or use -SkipPreflight only for local debugging." }
}

if ($Sign) {
    $SignTool = Find-SignTool
    $Description = "Qubit Coin Core v$Version"
    $ExeFiles = @((Join-Path $Dist 'QUB-Core.exe'), (Join-Path $Dist 'tools\qubd.exe'))
    foreach ($Exe in $ExeFiles) {
        if (-not (Test-Path $Exe)) { throw "Missing executable to sign: $Exe" }
        $SignArgs = @('sign', '/fd', 'SHA256', '/td', 'SHA256', '/tr', $TimestampUrl, '/d', $Description)
        if ($CertThumbprint -ne '') { $SignArgs += @('/sha1', $CertThumbprint) }
        elseif ($CertSubject -ne '') { $SignArgs += @('/n', $CertSubject) }
        else { $SignArgs += @('/a') }
        $SignArgs += $Exe
        & $SignTool @SignArgs
        if ($LASTEXITCODE -ne 0) { throw "signtool failed for $Exe" }
        & $SignTool verify /pa /v $Exe
        if ($LASTEXITCODE -ne 0) { throw "signtool verify failed for $Exe" }
    }
}

$HashFile = Join-Path $Dist 'SHA256SUMS.txt'
Get-ChildItem $Dist -Recurse -File | Where-Object { $_.Name -ne 'SHA256SUMS.txt' } | ForEach-Object {
    $hash = Get-FileHash -Algorithm SHA256 $_.FullName
    "$($hash.Hash.ToLower())  $($_.FullName.Substring($Dist.Length + 1))"
} | Set-Content -Encoding ASCII $HashFile

if ($BuildInstaller) {
    $ISCC = 'iscc.exe'
    $Iss = Join-Path $Root 'installer\QUB-Core.iss'
    if (-not (Test-Path $Iss)) { throw "Missing installer script: $Iss" }
    & $ISCC "/DMyAppSource=$Dist" "/DMyAppConfig=$Config" $Iss
    if ($LASTEXITCODE -ne 0) { throw 'Inno Setup compiler failed' }

    $InstallerName = "QUB-Core-v$Version-Windows-x64-$Config-Setup.exe"
    $InstallerPath = Join-Path $DistRoot "installer\$InstallerName"
    if (-not (Test-Path $InstallerPath)) { throw "Installer not found after ISCC: $InstallerPath" }

    if ($Sign) {
        $SignTool = Find-SignTool
        $Description = "Qubit Coin Core v$Version Installer"
        $SignArgs = @('sign', '/fd', 'SHA256', '/td', 'SHA256', '/tr', $TimestampUrl, '/d', $Description)
        if ($CertThumbprint -ne '') { $SignArgs += @('/sha1', $CertThumbprint) }
        elseif ($CertSubject -ne '') { $SignArgs += @('/n', $CertSubject) }
        else { $SignArgs += @('/a') }
        $SignArgs += $InstallerPath
        & $SignTool @SignArgs
        if ($LASTEXITCODE -ne 0) { throw "signtool failed for installer $InstallerPath" }
        & $SignTool verify /pa /v $InstallerPath
        if ($LASTEXITCODE -ne 0) { throw "signtool verify failed for installer $InstallerPath" }
    }

    $LatestExe = Join-Path $DistRoot 'updates\QUB-Core-Latest.exe'
    Copy-Item $InstallerPath $LatestExe -Force
    $LatestHash = (Get-FileHash -Algorithm SHA256 $LatestExe).Hash.ToLower()
    Set-Content -Encoding ASCII (Join-Path $DistRoot 'updates\QUB-Core-Latest.exe.sha256') $LatestHash

    $VersionedUpdateInstaller = Join-Path $ChannelUpdateDir $InstallerName
    $ChannelLatest = Join-Path $ChannelUpdateDir 'QUB-Core-Latest.exe'
    Copy-Item $InstallerPath $VersionedUpdateInstaller -Force
    Copy-Item $InstallerPath $ChannelLatest -Force
    $VersionedHash = (Get-FileHash -Algorithm SHA256 $VersionedUpdateInstaller).Hash.ToLower()
    $ChannelLatestHash = (Get-FileHash -Algorithm SHA256 $ChannelLatest).Hash.ToLower()
    Set-Content -Encoding ASCII (Join-Path $ChannelUpdateDir "$InstallerName.sha256") $VersionedHash
    Set-Content -Encoding ASCII (Join-Path $ChannelUpdateDir 'QUB-Core-Latest.exe.sha256') $ChannelLatestHash

    $ConsensusFamily = if ($Config -eq 'mainnet') { 'qns-1000' } elseif ($Config -eq 'testnet') { 'qns-50' } else { $Config }
    $Manifest = [ordered]@{
        channel = "$Config-windows-x64"
        network = $Config
        version = $Version
        platform = 'windows-x64'
        kind = 'installer'
        mandatory = $false
        consensus_family = $ConsensusFamily
        published_at = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
        url = "$UpdateBaseUrl/$Config/windows-x64/$InstallerName"
        latest_url = "$UpdateBaseUrl/$Config/windows-x64/QUB-Core-Latest.exe"
        sha256 = $VersionedHash
        notes = 'Manifest-based private QUB Core updater. Unsigned private builds are allowed only for the closed miner group until Authenticode signing is ready.'
    }
    $ManifestJson = $Manifest | ConvertTo-Json -Depth 8
    $ManifestPath = Join-Path $ChannelUpdateDir 'manifest.json'
    $Utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($ManifestPath, $ManifestJson, $Utf8NoBom)
    $ManifestHash = (Get-FileHash -Algorithm SHA256 $ManifestPath).Hash.ToLower()
    Set-Content -Encoding ASCII (Join-Path $ChannelUpdateDir 'manifest.json.sha256') $ManifestHash
}

Write-Host "Built release bundle: $Dist"
Write-Host "Normal users run: $Dist\QUB-Core.exe"
Write-Host "Advanced tools: $Dist\tools"
if ($BuildInstaller) {
    Write-Host "Installer ready: $DistRoot\installer\QUB-Core-v$Version-Windows-x64-$Config-Setup.exe"
    Write-Host "Legacy latest payload: $DistRoot\updates\QUB-Core-Latest.exe"
    Write-Host "Manifest channel output: $DistRoot\updates\$Config\windows-x64\manifest.json"
}
if ($Sign) { Write-Host "Executables were Authenticode-signed before SHA256SUMS.txt was generated." }
